import React from "react";
import pic from "./img/trade.avif";
import prot from "./img/portf.avif";
import btc from "./img/btc.avif";

const Sdata =[
    {
        imgsrc: btc,
        title: "Basic to Advance Technical Analysis",
        data:"Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume."
    },
    {
        imgsrc: prot,
        title: "Protfolio Management",
        data:"Portfolio management is the process of managing a collection of investments, such as stocks, bonds, and other assets, to achieve a specific financial goal"
    }
]

export default Sdata